Add sentence transformers, cause:
docker container stops with the following error:

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/app/server.py", line 7, in <module>
    from mylibs.rag_chroma.chain import chain as rag_chroma_chain
  File "/code/mylibs/rag_chroma/chain.py", line 15, in <module>
    vectorstore = get_vectorstore()
                  ^^^^^^^^^^^^^^^^^
  File "/code/mylibs/embedding/embedding.py", line 70, in get_vectorstore
    db_embedding = embedding()
                   ^^^^^^^^^^^
  File "/code/mylibs/embedding/embedding.py", line 28, in embedding
    return HuggingFaceBgeEmbeddings(model_name=settings.embedding_model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/embeddings/huggingface.py", line 227, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.